[package]
name = "lesson_03_subscriber_rcllibrust"
version = "0.1.0"
edition = "2021"

[dependencies]
roslibrust = { git = "https://github.com/RosLibRust/roslibrust", package = "roslibrust", features = ["rosbridge"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "signal"] }
env_logger = "0.11"
utils_rcllibrust = { path = "../utils_rcllibrust" }

[build-dependencies]
roslibrust = { git = "https://github.com/RosLibRust/roslibrust", package = "roslibrust", features = ["codegen"] }
