[package]
name = "utils_roslibrust"
version = "0.1.0"
edition = "2021"

[dependencies]
roslibrust = { version = "0.18", features = ["rosbridge"] }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tokio = { version = "1", features = ["full"] }
