[package]
name = "lesson_03_subscriber_rclrs"
version = "0.1.0"
edition = "2021"

[dependencies]
rclrs = "0.6"
utils_rclrs = { path = "../utils_rclrs" }
lesson_interfaces = { path = "../../../../install/lesson_interfaces/share/lesson_interfaces/rust" }