[package]
name = "lesson_03_subscriber_rclrs"
version = "0.1.0"
edition = "2021"

[dependencies]
rclrs = { git = "https://github.com/ros2-rust/ros2_rust", tag = "v0.6.0", package = "rclrs" }
std_msgs = "*"
utils_rclrs = { path = "../utils_rclrs" }
