[package]
name = "lesson_05_parameters_rclrs"
version = "0.1.0"
edition = "2021"

[dependencies]
# ROS 2 Client Library
rclrs = "0.6"

# RCLRS extension for parameter support
rosrustext_rosrs = { version = "0.3.0", features = ["ros2"] }

# Utilities
anyhow = "1.0"
utils_rclrs = { path = "../utils_rclrs" }

# Message Interfaces (Locally Generated)
lesson_interfaces = { path = "../../../../install/lesson_interfaces/share/lesson_interfaces/rust" }
rcl_interfaces = { path = "../../../../install/rcl_interfaces/share/rcl_interfaces/rust" }

[lib]
name = "lesson_05_logic"
path = "src/lib.rs"

[[bin]]
name = "lesson_05_publisher"
path = "src/bin/lesson_05_publisher.rs"

[[bin]]
name = "lesson_05_subscriber"
path = "src/bin/lesson_05_subscriber.rs"


