[package]
name = "lesson_03_sub_rcllibrust"
version = "0.1.0"
edition = "2021"

[dependencies]
roslibrust = { version = "0.18", features = ["rosbridge"] }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
utils_roslibrust = { path = "../utils_roslibrust" }
futures = "0.3"