[package]
name = "lesson_05_roslibrust"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async Runtime
tokio = { version = "1", features = ["full"] }
futures = "0.3" 

# ROS & Logging
roslibrust = "0.18"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

# Workspace dependencies
utils_roslibrust = { path = "../utils_roslibrust" }
serde_json = "1.0.149"

[lib]
name = "lesson_05_roslibrust"
path = "src/lib.rs"

[[bin]]
name = "publisher"
path = "src/bin/publisher.rs"

[[bin]]
name = "subscriber"
path = "src/bin/subscriber.rs"
